<?php

declare(strict_types=1);

namespace MohamedSamy902\LaravelMediaVault\Services;

class MediaSourceManager
{
    /**
     * @var array<string>
     */
    protected array $registeredModels = [];

    /**
     * @var bool
     */
    protected bool $isLoaded = false;

    /**
     * Load models from cache and config.
     */
    public function loadModels(): void
    {
        if ($this->isLoaded) {
            return;
        }

        // 1. Load from cache (generated by discovery command)
        $cachePath = base_path('bootstrap/cache/media-vault-models.php');
        if (file_exists($cachePath)) {
            $cachedModels = require $cachePath;
            if (is_array($cachedModels)) {
                $this->registeredModels = array_merge($this->registeredModels, $cachedModels);
            }
        }

        // 2. Load from config (manual fallback)
        $configModels = config('media-vault.media_models', []);
        foreach ($configModels as $modelClass => $fields) {
            if (!in_array($modelClass, $this->registeredModels, true)) {
                $this->registeredModels[] = $modelClass;
            }
        }

        $this->registeredModels = array_unique($this->registeredModels);
        $this->isLoaded = true;
    }

    /**
     * Dynamically register a model class (e.g., from the trait boot method).
     *
     * @param string $modelClass
     */
    public function registerModel(string $modelClass): void
    {
        if (!in_array($modelClass, $this->registeredModels, true)) {
            $this->registeredModels[] = $modelClass;
        }
    }

    /**
     * Get all registered custom model classes.
     *
     * @return array<int, class-string<\Illuminate\Database\Eloquent\Model>>
     */
    public function getRegisteredModels(): array
    {
        $this->loadModels();
        /** @var array<int, class-string<\Illuminate\Database\Eloquent\Model>> */
        return $this->registeredModels;
    }

    /**
     * Resolve the fields configuration for a specific model.
     *
     * @param class-string<\Illuminate\Database\Eloquent\Model> $modelClass
     * @return array<string, array<string, mixed>>
     */
    public function getModelFields(string $modelClass): array
    {
        // Check manual config first
        $configModels = config('media-vault.media_models', []);
        if (isset($configModels[$modelClass])) {
            return $configModels[$modelClass];
        }

        // Check if model has the trait
        if (method_exists($modelClass, 'getMediaFieldsDefinition')) {
            $instance = new $modelClass;
            return $instance->getMediaFieldsDefinition();
        }

        return [];
    }
}
